server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/lab3_access.log;
    error_log  /var/log/nginx/lab3_error.log;

    # Frontend estático
    root /var/www/lab3;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy al microservicio de alertas
    location /api/alerts/ {
        proxy_pass http://127.0.0.1:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy al microservicio de acciones
    location /api/actions/ {
        proxy_pass http://127.0.0.1:5001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
